// microfrontends/remote-vue-chat/src/components/App.vue
<template>
  <div id="app">
    <h2>VUE chat</h2>
    <form v-on:submit.prevent="onSubmit">
      <input type="text" v-model="text" placeholder="Type a message..." />
      <button>Send</button>
    </form>
    <ul>
      <li v-for="message in messages" :key="message.id">
        {{ message.createdAt.getHours() }}:{{ message.createdAt.getMinutes() }}
        {{ message.text }}
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      messages: [],
      text: "",
      id: 1,
    };
  },
  methods: {
    onSubmit() {
      if (this.text.length > 0) {
        const newMessage = {
          id: this.id,
          author: this.name,
          text: this.text,
          createdAt: new Date(),
        };
        this.messages.push(newMessage);
        this.text = "";
        this.id = this.id + 1;
      }
    },
  },
};
</script>

// microfrontends/remote-react-chat/src/components/App.tsx
import React, { useState } from "react";
import { useSharedValue } from "reactive-map";

export function App() {
  const [messages, setMessages] = useState([]);
  const [newMessage, setNewMessage] = useState("");
  const currentUsername = useSharedValue("username");

  return (
    <>
      <h2>{currentUsername}'s React chat</h2>
      {messages.map((message) => (
        <p key={message.sentAt.getTime()}>{message.text}</p>
      ))}
      <form
        onSubmit={(e) => {
          e.preventDefault();
          setMessages([...messages, { text: newMessage, sentAt: new Date() }]);
          setNewMessage("");
        }}
      >
        <input
          type="text"
          name="text"
          value={newMessage}
          onChange={(e) => setNewMessage(e.target.value)}
        />
        <button type="submit">Send</button>
      </form>
    </>
  );
}
